apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme"
spec: 
  selector:
    matchLabels:
      app: "acme"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "acme"
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: "acme"
        env:
          - name: DB_HOSTNAME
            value: {{ .Values.dbhost }}
          - name: DB_USERNAME
            value: {{ .Values.dbname }}
          - name: DB_PASSWORD
            value: {{ .Values.dbpass }}
          - name: DB_NAME
            value: {{ .Values.name }}
        ports:
        - containerPort: 80
